name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js versão 16 ou mais recente

      - name: Instalar dependências do projeto
        run: |
          cd app
          npm install

      - name: Configurar husky
        run: |
          cd app
          npm run prepare

      - name: Configurar commitlint
        run: |
          cd app
          echo "module.exports = {extends: ['@commitlint/config-conventional'], rules: { 'subject-empty': [0, 'never'], 'type-empty': [0, 'never'] }};" > commitlint.config.js

      - name: Verificação de commitlint
        run: |
          cd app
          git log -1 --pretty=%B | npx commitlint

      - name: Rodar ESLint
        run: |
          cd app
          npm run lint

      - name: Rodar testes com Jest
        run: |
          cd app
          npm test

      - name: Construir o projeto
        run: |
          cd app
          npm run build

      - name: Implantar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build # ajuste para o diretório de build do seu projeto
