name: Verificação Semântica

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar commitlint
      run: npm install @commitlint/config-conventional @commitlint/cli husky --save-dev

    - name: Configurar commitlint
      run: echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js

    - name: Adicionar hook do husky
      run: npx husky install && npx husky add .husky/commit-msg "npx --no-install commitlint --edit $1"

    - name: Verificação de commitlint
      run: npx commitlint --from=HEAD~1 --to=HEAD
